name: Hello from GH

on:[push]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      -name: say Hello
        run: echo "Hello from GitHub!!!"
      -name: show Date
        run: date
      -name: list Files
        run: ls -la  