name: Multi-Job pipeline

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run linter
      - uses: actions/@checkout@v3
        run: echo "Linting code ..."

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
      - uses: actions/@checkout@v3
        run: echo "Running tests ..."

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Build application
      - uses: actions/@checkout@v3
        run: echo "Building app ..."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to production
        run: echo "Deploying to production ..."
